### ISSUE TITLE
Add option to disable zil checksum

### ISSUE THREAD

**Issue by reb0rn21** [cryptolandtech/moonlet#170]
Is there any way to disable checksum check as public proxy/pool for zilliqa mining has all addresses in lowercase?

**Comment by krisboit** [comment]
there is no way to disable checksum for the moment, but you can go to https://viewblock.io search your address and there you have your checksum valid address.

**Comment by i3uRi** [comment]
That’s an interesting idea. However we had decided to protect users during Zilliqa’s swapping phase and use the checksum. We will add it to our backlog and potentially add a switch button underneath Developer mode. Not sure when we will be able to tackle it since we are preparing for releasing new features in the following weeks.

**Comment by reb0rn21** [comment]
Ok tnx atm I am loading older version as converting ~40 address would take some time
